# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Pair.create(left_attributes: {text: "Clean up Fang's slobber"}, right_attributes: {text: "Give Buckbeak a pedicure"})
Pair.create(left_attributes: {text: "Have tea wih Trelawney"}, right_attributes: {text: "Do a book signing with Lockhart"})
Pair.create(left_attributes: {text: "Eat one of Hagrid's rockcakes"}, right_attributes: {text: "Eat a cockroach cluster"})
Pair.create(left_attributes: {text: "Wear Dobby's tea cozy"}, right_attributes: {text: "Wear Winky's 'sad' dress"})
Pair.create(left_attributes: {text: "Change Slughorn's bedpan"}, right_attributes: {text: "Clean Mrs. Norris' litter box"})
Pair.create(left_attributes: {text: "Shove a bezoar down someone's throat"}, right_attributes: {text: "Drain buber-tuber pus from someone's fingers"})
Pair.create(left_attributes: {text: "Walk through a ghost"}, right_attributes: {text: "Accidentally touch a Portkey"})
Pair.create(left_attributes: {text: "Have the Elder Wand"}, right_attributes: {text: "Have the Invisibility Cloak"})
Pair.create(left_attributes: {text: "Ride a broom to London"}, right_attributes: {text: "Take a Flying Car to London"})
Pair.create(left_attributes: {text: "Ride a Hippogryff"}, right_attributes: {text: "Ride a Thestral"})
Pair.create(left_attributes: {text: "Clip Grawp's toenails"}, right_attributes: {text: "Take a Skrewt for a walk"})
Pair.create(left_attributes: {text: "Fail all your OWLs"}, right_attributes: {text: "Never get a Hogwarts letter"})
Pair.create(left_attributes: {text: "Break Dumbledore's Pensieve"}, right_attributes: {text: "Loose your Invisibility Cloak"})
Pair.create(left_attributes: {text: "Drink Veritas Serum"}, right_attributes: {text: "Drink an out of date Love Potion"})
Pair.create(left_attributes: {text: "Be sent to Azkaban"}, right_attributes: {text: "Be sent to the Dursley's"})
Pair.create(left_attributes: {text: "Go to the Yuleball with Cedric Diggory"}, right_attributes: {text: "Go to the Yuleball with Viktor Krum"})
Pair.create(left_attributes: {text: "Walkz with Madame Maxime"}, right_attributes: {text: "Two-Step with Mad-Eye Moody"})
Pair.create(left_attributes: {text: "Try to reason with Luna Lovegood"}, right_attributes: {text: "Talk Quidditch with Cormac McClaggen"})
Pair.create(left_attributes: {text: "Be hit with a Bludger"}, right_attributes: {text: "Attacked by Hermione's canaries"})
Pair.create(left_attributes: {text: "Duel with Bellatrix Lastrange"}, right_attributes: {text: "Be reprimanded by McGonnagal"})
Pair.create(left_attributes: {text: "Do detention with Snape"}, right_attributes: {text: "Do lines for Umbridge"})
Pair.create(left_attributes: {text: "Kiss a Dementor"}, right_attributes: {text: "Milk Nagini"})
Pair.create(left_attributes: {text: "Ride a centaur"}, right_attributes: {text: "Be carried by Aragog (an Acrumantula)"})
Pair.create(left_attributes: {text: "Spend all your money on a Firebolt"}, right_attributes: {text: "Give all your money to the Weasleys"})
Pair.create(left_attributes: {text: "Wear Ron's dress robes"}, right_attributes: {text: "Wear Dudley's hand-me-downs"})
Pair.create(left_attributes: {text: "Visit the Shrieking Shack"}, right_attributes: {text: "Have a drink at the Three Broomsticks"})
Pair.create(left_attributes: {text: "Take a wrong turn down Nocturne Alley"}, right_attributes: {text: "Miss the Hogwarts Express"})
Pair.create(left_attributes: {text: "Become a part-owner in Weasley's Wizard Weezes"}, right_attributes: {text: "Invent the Sorceror's Stone"})
Pair.create(left_attributes: {text: "Listen to Celestina Warbeck"}, right_attributes: {text: "Dogged by Ramilda Vein"})
Pair.create(left_attributes: {text: "Place a bet with Ludo Bagman"}, right_attributes: {text: "Report to Barty Crouch"})
Pair.create(left_attributes: {text: "Fight a Hungarian Horntail"}, right_attributes: {text: "Ask a girl to the Yuleball"})
Pair.create(left_attributes: {text: "Win the Tri-Wizard Tournament"}, right_attributes: {text: "Beat Draco Malfoy at Quidditch"})
Pair.create(left_attributes: {text: "Be Hogwarts Prefect"}, right_attributes: {text: "Named Captain of Gryffandor Quidditch team"})
Pair.create(left_attributes: {text: "Play Quidditch seeker"}, right_attributes: {text: "Play Quidditch keeper"})
Pair.create(left_attributes: {text: "Go to the Yuleball with Moaning Myrtle"}, right_attributes: {text: "Meet Eloise Midgen at Madame Puddifoots"})
Pair.create(left_attributes: {text: "Have your birthday at the Weasley's"}, right_attributes: {text: "Have Christmas at Hogwarts"})
Pair.create(left_attributes: {text: "Fight off a Grindylow"}, right_attributes: {text: "Get stung by a Doxie"})
Pair.create(left_attributes: {text: "Be on a Chocolate Frog Card"}, right_attributes: {text: "Lead the Wizengammot"})
Pair.create(left_attributes: {text: "Aim to kill with Avada Kadavra"}, right_attributes: {text: "Aim to disarm with Expelliarmus"})
Pair.create(left_attributes: {text: "Be a member of the 'Slug Club'"}, right_attributes: {text: "Be a member of Dumbledore's Army"})
Pair.create(left_attributes: {text: "Have the Maurauder's Map"}, right_attributes: {text: "Have Aberforth Dumbledor's 2-Way Mirror"})
Pair.create(left_attributes: {text: "Be a member of the Order of the Phoenix"}, right_attributes: {text: "Be a Death Eater"})
Pair.create(left_attributes: {text: "Live in Otter Saint Catchpole"}, right_attributes: {text: "Live in Godric's  Hollow"})
Pair.create(left_attributes: {text: "Talk  history with Bathilda Bagshot"}, right_attributes: {text: "Gossip with Auntie Murial"})
Pair.create(left_attributes: {text: "Write for the Daily Prophet"}, right_attributes: {text: "Write for the Quibbler"})
Pair.create(left_attributes: {text: "Clean up after Fluffy, the Three Headed Dog"}, right_attributes: {text: "Raise Aragog from an egg"})
Pair.create(left_attributes: {text: "Talk to snakes"}, right_attributes: {text: "Be incapable of producing a Patronus"})
Pair.create(left_attributes: {text: "Be a squib"}, right_attributes: {text: "Be a Muggle, with no knowledge of the Wizarding World"})
Pair.create(left_attributes: {text: "Work at Gringots"}, right_attributes: {text: "Be a dragon trainer"})
Pair.create(left_attributes: {text: "Attend Beaubaton's Academy"}, right_attributes: {text: "Attend Durmstrang Institute"})